import { FormEvent, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api, errorMessage } from '../../lib/api';

type Item = { id: string; name: string; category: string; color: string; style: string; imageUrl: string | null; purchaseUrl: string | null; minTemp: number; maxTemp: number; waterproof: boolean };
const labels: Record<string, string> = { TOP: 'Áo', BOTTOM: 'Quần', OUTERWEAR: 'Áo khoác', SHOES: 'Giày', ACCESSORY: 'Phụ kiện', CASUAL: 'Thoải mái', STREETWEAR: 'Đường phố', FORMAL: 'Lịch sự', SPORT: 'Thể thao', MINIMAL: 'Tối giản' };

export function WardrobePage() {
  const client = useQueryClient(); const items = useQuery({ queryKey: ['wardrobe'], queryFn: async () => (await api.get<Item[]>('/wardrobe')).data }); const [adding, setAdding] = useState(false); const [editing, setEditing] = useState<Item | null>(null); const [loadingId, setLoadingId] = useState(''); const [imageErrors, setImageErrors] = useState<Record<string, string>>({}); const [manualId, setManualId] = useState(''); const [manualUrl, setManualUrl] = useState('');
  const refresh = () => client.invalidateQueries({ queryKey: ['wardrobe'] });
  async function loadImage(id: string) { setLoadingId(id); setImageErrors(errors => ({ ...errors, [id]: '' })); try { await api.post(`/wardrobe/${id}/resolve-image`); await refresh(); } catch (error) { setImageErrors(errors => ({ ...errors, [id]: errorMessage(error) })); } finally { setLoadingId(''); } }
  async function saveManual(event: FormEvent<HTMLFormElement>, id: string) { event.preventDefault(); setLoadingId(id); setImageErrors(errors => ({ ...errors, [id]: '' })); try { await api.patch(`/wardrobe/${id}/image`, { imageUrl: manualUrl }); setManualId(''); setManualUrl(''); await refresh(); } catch (error) { setImageErrors(errors => ({ ...errors, [id]: errorMessage(error) })); } finally { setLoadingId(''); } }
  if (items.isPending) return <section className="placeholder"><p>Đang mở tủ đồ của bạn…</p></section>;
  if (items.isError) return <section className="placeholder"><p>{errorMessage(items.error)}</p></section>;
  return <section className="wardrobe-page"><div className="wardrobe-intro"><div><p className="eyebrow">TỦ ĐỒ CỦA BẠN</p><h1>Những món bạn<br />muốn mặc.</h1><p>Mỗi món đồ sẽ giúp gợi ý trang phục phù hợp hơn với thời tiết.</p></div><button className="text-button" onClick={() => { setAdding(!adding); setEditing(null); }}>{adding ? 'Đóng biểu mẫu' : '+ Thêm món đồ'}</button></div>
    {adding && <ItemForm onSaved={() => { setAdding(false); void refresh(); }} onCancel={() => setAdding(false)} />}{editing && <ItemForm item={editing} onSaved={() => { setEditing(null); void refresh(); }} onCancel={() => setEditing(null)} />}
    {items.data?.length ? <div className="wardrobe-grid">{items.data.map(item => <article className="clothing-card" key={item.id}>{item.imageUrl ? <img className="clothing-photo" src={item.imageUrl} alt={item.name} /> : <div className="clothing-photo clothing-photo-empty"><span>👖</span>{manualId === item.id ? <form className="manual-image-form" onSubmit={event => void saveManual(event, item.id)}><input aria-label="Link ảnh" type="url" required autoFocus placeholder="Dán link ảnh https://…" value={manualUrl} onChange={event => setManualUrl(event.target.value)} /><div><button type="submit" disabled={loadingId === item.id}>{loadingId === item.id ? 'Đang lưu…' : 'Lưu ảnh'}</button><button type="button" onClick={() => { setManualId(''); setManualUrl(''); }}>Hủy</button></div></form> : <><button type="button" disabled={loadingId === item.id} onClick={() => void loadImage(item.id)}>{loadingId === item.id ? 'Đang lấy ảnh…' : 'Lấy ảnh sản phẩm'}</button><button className="manual-image-button" type="button" onClick={() => setManualId(item.id)}>Dán link ảnh thủ công</button></>}{imageErrors[item.id] && <small className="image-error">{imageErrors[item.id]}</small>}</div>}<div className="clothing-card-body"><span className="clothing-category">{labels[item.category] ?? item.category}</span><h2>{item.name}</h2><p className="clothing-meta">{item.color} · {labels[item.style] ?? item.style}</p><p className="clothing-meta">{item.minTemp}–{item.maxTemp}°C{item.waterproof ? ' · Chống nước' : ''}</p><div className="clothing-actions"><button type="button" onClick={() => { setEditing(item); setAdding(false); }}>Chỉnh sửa</button>{item.purchaseUrl && <a className="clothing-link" href={item.purchaseUrl} target="_blank" rel="noreferrer">Xem sản phẩm ↗</a>}</div></div></article>)}</div> : <div className="empty-wardrobe"><span>👚</span><h2>Tủ đồ đang chờ bạn.</h2><p>Thêm món đồ đầu tiên để chuẩn bị cho gợi ý trang phục.</p></div>}
  </section>;
}

function ItemForm({ item, onSaved, onCancel }: { item?: Item; onSaved: () => void; onCancel: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const editing = Boolean(item);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget); const data = { name: form.get('name'), category: form.get('category'), color: form.get('color'), style: form.get('style'), minTemp: Number(form.get('minTemp')), maxTemp: Number(form.get('maxTemp')), purchaseUrl: form.get('purchaseUrl') || undefined, imageUrl: form.get('imageUrl') || undefined, waterproof: form.get('waterproof') === 'on' }; try { if (item) await api.patch(`/wardrobe/${item.id}`, data); else await api.post('/wardrobe', data); onSaved(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <form className="account-form add-clothing-form" onSubmit={submit}><h2>{editing ? 'Chỉnh sửa món đồ' : 'Thêm vào tủ đồ'}</h2><p className="muted">Bạn có thể thay đổi mọi thông tin và ảnh bất cứ lúc nào.</p><div className="form-two-columns"><label>Tên món đồ<input name="name" required maxLength={120} defaultValue={item?.name} /></label><label>Link sản phẩm<input name="purchaseUrl" type="url" maxLength={2048} defaultValue={item?.purchaseUrl ?? ''} placeholder="https://…" /></label><label>Link ảnh thủ công<input name="imageUrl" type="url" maxLength={2048} defaultValue={item?.imageUrl ?? ''} placeholder="https://…" /></label><label>Loại<select name="category" defaultValue={item?.category ?? 'BOTTOM'}><option value="TOP">Áo</option><option value="BOTTOM">Quần</option><option value="OUTERWEAR">Áo khoác</option><option value="SHOES">Giày</option><option value="ACCESSORY">Phụ kiện</option></select></label><label>Màu<input name="color" required maxLength={40} defaultValue={item?.color} placeholder="Đen" /></label><label>Phong cách<select name="style" defaultValue={item?.style ?? 'CASUAL'}><option value="CASUAL">Thoải mái</option><option value="STREETWEAR">Đường phố</option><option value="FORMAL">Lịch sự</option><option value="SPORT">Thể thao</option><option value="MINIMAL">Tối giản</option></select></label><label>Nhiệt độ tối thiểu<input name="minTemp" type="number" defaultValue={item?.minTemp ?? 20} min="-20" max="60" required /></label><label>Nhiệt độ tối đa<input name="maxTemp" type="number" defaultValue={item?.maxTemp ?? 35} min="-20" max="60" required /></label></div><label className="check"><input name="waterproof" type="checkbox" defaultChecked={item?.waterproof} /> Chống nước</label>{error && <p className="form-error">{error}</p>}<div className="form-actions"><button className="button" disabled={busy}>{busy ? 'Đang lưu…' : editing ? 'Lưu thay đổi' : 'Lưu vào tủ đồ'}</button><button className="text-button" type="button" onClick={onCancel}>Hủy</button></div></form>;
}
