import { FormEvent, useState } from 'react';
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom';
import { useQueryClient } from '@tanstack/react-query';
import { errorMessage } from '../../lib/api';
import { authenticate, useSession } from './session';

export function LoginPage({ mode }: { mode: 'login' | 'register' }) {
  const session = useSession(); const navigate = useNavigate(); const location = useLocation(); const client = useQueryClient(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const from = typeof location.state?.from === 'string' ? location.state.from : '/profile';
  if (session.loading) return <p className="placeholder">Đang kiểm tra phiên đăng nhập…</p>;
  if (session.user) return <Navigate to={from} replace />;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); try { if (mode === 'login') await authenticate('login', { identifier: String(form.get('identifier')), password: String(form.get('password')) }); else await authenticate('register', { email: String(form.get('email')), username: String(form.get('username')), password: String(form.get('password')) }); client.clear(); navigate(from, { replace: true }); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <section className="account-layout"><div className="account-intro"><p className="eyebrow">MỘT GÓC NHỎ DÀNH RIÊNG CHO BẠN</p><h1>{mode === 'login' ? 'Chào bạn,\nmừng trở lại.' : 'Gieo một hạt mầm\ncho hôm nay.'}</h1><p>Lưu lại những ngày của bạn, chăm một khu vườn và tìm niềm vui từ những điều giản dị.</p><div className="account-garden-art"><img src="/assets/login-garden-illustration.png" alt="Minh họa khu vườn đang lớn lên" /></div></div><form className="account-form" onSubmit={submit}><h2>{mode === 'login' ? 'Đăng nhập' : 'Tạo tài khoản'}</h2><p className="muted">{mode === 'login' ? 'Góc nhỏ của bạn đang chờ.' : 'Bắt đầu hành trình theo nhịp của riêng bạn.'}</p>{mode === 'register' && <><label>Tên người dùng<input name="username" required minLength={3} maxLength={30} pattern="[a-zA-Z0-9_]{3,30}" autoComplete="username" placeholder="ten_cua_ban" /></label><label>Email<input name="email" type="email" required maxLength={254} autoComplete="email" placeholder="ban@example.com" /></label></>} {mode === 'login' && <label>Tên người dùng hoặc email<input name="identifier" required minLength={3} maxLength={254} autoComplete="username" placeholder="emsidt hoặc ban@example.com" /></label>}<label>Mật khẩu<input name="password" type="password" required minLength={10} maxLength={128} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button" disabled={busy}>{busy ? 'Đang xử lý…' : mode === 'login' ? 'Đăng nhập' : 'Tạo khu vườn của bạn'}</button><p className="form-switch">{mode === 'login' ? 'Chưa có tài khoản? ' : 'Đã có tài khoản? '}<Link state={location.state} to={mode === 'login' ? '/register' : '/login'}>{mode === 'login' ? 'Đăng ký' : 'Đăng nhập'}</Link></p></form></section>;
}
